.TH anvil-daemon
.SH NAME
anvil-daemon - Main systemd daemon for the Anvil! IA platform. Provides all job management, monitoring and Striker back-end functions.
.SH SYNOPSIS
.B anvil-daemon
.SH DESCRIPTION
.B anvil-daemon
Main daemon for the M3 Anvil! Intelligent Availability\*(Tm platform. Usually managed via 
