.\" Manpage for the Anvil! storage groups
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH anvil-manage-storage-group "8" "March 23 2023" "Anvil! Intelligent Availability™ Platform"
.SH NAME
anvil-manage-storage-group \- This program manages if a server is (and when) a server is protected by a DR host.
.SH SYNOPSIS
.B anvil-manage-storage-group
\fI\,<command> \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
This tool manages storage groups. Storage Groups are collections of LVM Volume Groups across sub-nodes and DR hosts. A server's virtual hard disk syncs across LVs in common storage groups.
.IP
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log\-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.IP
.SS "Commands:"
\fB\-\-add\fR
When managing a Storage Group, this adds a component, like a volume group.
.TP
This can also be used to create a new Storage Group on a given Anvil! node. Requires \fB\-\-group <name>\fR.
.TP
\fB\-\-anvil <name or UUID>\fR
This is the Anvil! node whose storage groups you want to see or work on.
.TP
\fB\-\-remove <group name or UUID>\fR
This deletes a storage group entirely.
.TP
\fB\-\-rename\fR
This is used along with \fB\-\-new\-name <new name>\fR and \fB\-\-group <name or UUID>\fR to change the name of an existing storage group.
.TP
\fB\-\-group <name or UUID>\fR
The is the storage group name or UUID that is being worked with.
.TP
\fB\-\-member <VG internal UUID>\fR
This is the LVM volume group's 
.B internal
UUID (as shown by \fBvgdisplay\fR or with \fB\-\-show\fR. It is used to specify which volume group is being added or removed.
.TP
\fB\-\-new\-name <new name>\fR
When used with \fB\-\-rename\fR and \fB\-\-group <name or UUID>\fR, this specifies the new storage group name.
.TP
\fB\-\-show\fR
This shows the storage groups on each Anvil! node (or just the one specified with \fB\-\-anvil <name or UUID>\fR), and the available DR hosts.
.TP
.SH EXAMPLES

.RE
Add a VG to a storage group

.RS
anvil-manage-storage-groups --anvil vm-anvil-01 --group "Storage group 1" --add --member edrYMv-Fl2D-o0tO-g8ok-idOh-oBIh-65LuD6
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
