.\" Manpage for the Anvil! cluster update tool.
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH anvil-monitor-network "8" "July 24 2024" "Anvil! Intelligent Availability™ Platform"
.SH NAME
anvil-monitor-network \- Tool that watches for changes to any network interface on the system
.SH SYNOPSIS
.B anvil-monitor-network 
\fI\,<command> \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
This tool is meant to be run as a daemon. It will collect data on all interface on the host, and then start watching for any changes to those interfaces. Each time a change in state is detected (like a cable being unplugged or plugged in), 'scan-network' will be called. This will keep the Anvil! database up to date with the changes in the network, required for tasks like mapping the network interfaces of new hosts.
.IP
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log\-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.IP
.SS "Commands:"
This tool takes no switches.
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
