.\" Manpage for the Anvil! IA platform 
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH anvil-pcs-wrapper "8" "August 15 2024" "Anvil! Intelligent Availability™ Platform"
.SH NAME
anvil-pcs-wrapper \- Tools to prevent parallel runs of 'pcs'.
.SH SYNOPSIS
.B anvil-pcs-wrapper 
\fI\,<command>
.SH DESCRIPTION
To prevent issues with 'pcs' caused by too many simultaneous calls, this wrapper uses 'flock' to prevent parallel calls, except when called with 'pcs status'.
.B Note
This is a simple wrapper and takes no switches of its own. All switches are passed through to pcs.
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
