.\" Manpage for the Anvil! server boot program
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH anvil-change-password "8" "August 02 2022" "Anvil! Intelligent Availability™ Platform"
.SH NAME
anvil-change-password \- Tool used to change / reset the main Anvil! password.
.SH SYNOPSIS
.B anvil-change-password 
\fI\,<command> \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
anvil-change-password \- This is used to change / reset the password on a Striker dashboard. Alternatively, if '--anvil' is used, to change / reset the password on an Anvil! node pair.
.TP
Note: This password is used for the shell users, for the postgresql user and, when setting an Anvil! password, for the IPMI BMC user. In the later case, passwords over 16 characters will be truncated. Allowed characters are set by the limits on normal shell passwords.
.IP
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log\-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.IP
.SS "Commands:"
\fB\-\-anvil\fR <name|uuid>
When set, this changes the password on the target Anvil! sub-cluster. This is the Anvil! sub-cluster name (ie: 'an-anvil-01') or the Anvil! UUID. 
.TP
When not set, the Striker dashboard this command is run on will have it's passwords updated.
.TP
\fB\-\-new\-password\fR <secret>
This is the new password to set. See '\fB\-\-password-file\fR' below for an alternate way to pass in the password. 
.TP
If not set, you will be prompted to enter the new password.
.TP
\fB\-\-password\-file\fR </path/to/file>
This is an alternative way to pass the new password to this program. If set, the file is read in and the file contents are used. Be sure to use one line only in the file.
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
