.\" Manpage for the Anvil! tool to cycle NICs on a kvm/qemu VM
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH anvil-cycle-vm-nics "8" "July 26 2023" "Anvil! Intelligent Availability™ Platform"
.SH NAME
anvil-cycle-vm-nics \- Tool used to unplug and plug virtual network cables into kvm/qemu VM network interfaces
.SH SYNOPSIS
.B anvil-cycle-vm-nics
\fI\,<server_name> \/\fR
.SH DESCRIPTION
anvil-cycle-vm-nics \- This tool makes it easier to map virtual network interfaces during the configuration of VMs in a virtual Anvil! cluster.
.TP
The tool takes the name of the server (as displayed in virsh) and the sole argument. There are no other commands.
.B Note
This cycles NICs connected to bridges with the prefix, in order, 'bcn', 'sn', 'ifn', and 'mn'. 
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
