.\" Manpage for the Anvil! maintenance mode tool.
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH anvil-maintenance-mode "8" "Aug 10 2023" "Anvil! Intelligent Availability™ Platform"
.SH NAME
anvil-maintenance-mode \- This program manages flagging a machine in an Anvil! cluster as being in maintenance mode
.SH SYNOPSIS
.B anvil-maintenance-mode 
\fI\,<command> \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
This can set or unset a machine in the Anvil! cluster as being in maintenance mode or not. When called without any switches, it reports if the machine is in maintenance mode or not.
.TP
.B Note:
Currently, "maintenance mode" is not fully implemented in the Anvil! cluster.
.IP
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log\-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.IP
.SS "Commands:"
\fB\-\-set\fR {0,1}
.TP
Passing '0' disables maintenance mode, '1' enables it. 
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
