.\" Manpage for the Anvil! IA platform 
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH fence_pacemaker "8" "August 15 2024" "Anvil! Intelligent Availability™ Platform"
.SH NAME
fence_pacemaker \- Tool used to fence DRBD resources in the Anvil! IA platform
.SH SYNOPSIS
.B fence_pacemaker 
\fI\,<command>
.SH DESCRIPTION
fence_pacemaker \- This tool acts between DRBD and pacemaker, fencing a resource when the peer becomes lost. If the referenced resource is found in pacemaker, a location constraint is placed. If not, the peer is power fenced.
.TP
.SH NOTE
This tool does not use the Anvil::Tools library, nor does it connect to the Anvil database. 
.IP
.SH OPTIONS
All values passed to this agent are done via environment variables. For more information, please see the LINBIT DRBD fence/unfence agent documentation.
.TP
See the comments here: https://github.com/LINBIT/drbd-utils/blob/master/scripts/drbd.ocf
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
