.\" Manpage for the ScanCore daemon. 
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH scancore "8" "July 29 2022" "Anvil! Intelligent Availability™ Platform"
.SH NAME
scancore \- ScanCore systemd daemon for the M3 Anvil! Cluster.
.SH SYNOPSIS
.B scancore 
\fI\,<command> \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
scancore \- ScanCore provides all of the decision engine logic that provides all of the autonomous operation logic. How exactly it behaves depends on whether it is running on a Striker dashboard, Anvil! sub-node or DR host.
.IP
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log\-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.IP
.SS "Commands:"
\fB\-\-purge\fR
If passed, all scancore agents will be invoked with '\fB\-\-purge\fR'. This will cause all ScanCore data to be purged from the databases.
.TP
\fB\-\-run-once\fR
This will tell the program to exit after one run of all scan agents and after doing to post-scan logic.
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
