.\" Manpage for the Striker purge tool
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH striker-purge-target "8" "April 11 2024" "Anvil! Intelligent Availability™ Platform"
.SH NAME
striker-purge-target \- This tool purges the target from all Anvil! databases.
.SH SYNOPSIS
.B striker-purge-target 
\fI\,<command> \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
This tool can be used to purge a host or an Anvil! node (and both subnodes) from the Anvil! database.
.TP
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.SS "Commands:"
\fB\-\-anvil\fR
.TP
This purges the Anvil! node (and both subnodes) from the Anvil! database.
.TP
\fB\-\-host\fR <host name or UUID>
.TP
This purges a specific host from the Anvil! databases.
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
