.\" Manpage for the Anvil! IA platform 
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH striker-show-jobs "8" "October 18 2023" "Anvil! Intelligent Availability™ Platform"
.SH NAME
striker-show-jobs \- This shows the queued, running and (recently) completed jobs.
.SH SYNOPSIS
.B striker-show-jobs 
\fI\,<command> \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
This shows information about jobs that are queued, running or completed within a set amount of time on the command line.
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.SS "Commands:"
\fB\-\-ended\-within\fR <seconds>
This allows viewing jobs that have already completed. This is the number of seconds (default '300') back in time that you want to see completed jobs. Jobs that completed more than this amount of time ago will be ignored.
.TP
\fB\-\-host\fR <name, UUID or 'all'>
This is the host name or UUID that you want to see jobs from. The default is 'all' and shows all machines in the Anvil! cluster.
.TP
Setting this to '0' will hide completed jobs.
\fB\-\-job\-uuid\fR <uuid>
This allows showing the details of only one specific job.
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
