.\" Manpage for the Anvil! server boot program
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH striker-boot-machine "8" "August 15 2024" "Anvil! Intelligent Availability™ Platform"
.SH NAME
striker-boot-machine \- Tool used to boot physical machines that have IPMI configuration information.
.SH SYNOPSIS
.B striker-boot-machine 
\fI\,<command> \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
This tool is used to power up any machine in the cluster with IPMI configuration in the database. Typically this is subnodes and DR hosts, but could also be Striker dashboards if they have an IPMI BMC. If the server is found to already be om, it will NOT be booted again.
.IP
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log\-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.IP
.SS "Commands:"
\fB\-\-host\fR <name, UUID or 'all'>
This is the host name or UUID of the server to power on. If this is set to 'all', all machines that have IPMI configuration information will be checked, and if it's found to be off, it will be booted.
.TP
\fB\-\-host-uuid\fR <UUID>
This is effectively the same as \fB\-\-host\fR, but provides backwards compatibility. Its use is discouraged.
.TP
\fB\-\-job\-uuid\fR <uuid>
If this is set, the job will be processed.
.TP
Be aware that when this is used, if a server fails to boot, no further servers will be started.
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
