.\" Manpage for the Anvil! IA platform 
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH striker-parse-oui "8" "August 15 2024" "Anvil! Intelligent Availability™ Platform"
.SH NAME
striker-parse-oui \- This parses the IEEE OUI file and parses it for storage in the Anvil database
.SH SYNOPSIS
.B striker-parse-oui 
\fI\,<command> \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
This tool downloads and parses the IEEE list of OUI vendors list. This is used to allow the Anvil! to map a MAC address to a vendor. 
.TP
.B Note
The list that is downloaded is - https://standards-oui.ieee.org/oui/oui.txt 
.TP
The oui.txt file is cached locally once downloaded to minimize loading the IEEE server. It will be redownloaded every few days.
.IP
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log\-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.IP
.SS "Commands:"
\fB\-\-force\fR
This forces a scan, even if it's not been 24 hours since the last time a scan completed.
.TP
\fB\-\-job\-uuid\fR <uuid>
This is the job UUID used to run this job.
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
