.\" Manpage for the Anvil! IA platform 
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH striker-get-peer-data "8" "February 19 2025" "Anvil! Intelligent Availability™ Platform"
.SH NAME
striker-get-peer-data \- This collects information from a target computer.
.SH SYNOPSIS
.B striker-get-peer-data 
\fI\,<command> \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
This is used to test a connection to a remote machine and, if it connects, information about the host is returned.
.IP
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.IP
.SS "Commands:"
.TP
\fB\-\-password\fR <password>
If the '\fB\-\-state\-uuid\fR' is not used, the alternative way to pass the password to use to connect to the \fB\-\-target\fR is using this switch. Be mindful of escaping or quoting the password as necessary.
.TP
\fB\-\-state\-uuid\fR <uuid>
If the password is stored in the database's 'states' table, this is the 'state_uuid' that points to the record with the password stored in the 'state_note'. Once this is read, the 'state_uuid' column is deleted, so it's one-use.
.TP
\fB\-\-target\fR [user@]<ip_or_hostname>[:port]
This is the target you want to collect data from.
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
