.\" Manpage for the Anvil! cluster update tool.
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH striker-update-cluster "8" "July 11 2023" "Anvil! Intelligent Availability™ Platform"
.SH NAME
striker-update-cluster \- This program updates all physical machines in an Anvil! cluster
.SH SYNOPSIS
.B striker-update-cluster 
\fI\,<command> \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
This program sequentially updates Striker dashboards, DR hosts and Anvil! nodes (the paired sub-nodes). It does this without needing to take hosted servers offline.
.TP
.B Note:
.TP
This program requires all machines be online, and Anvil! nodes being paired and sync'ed. When nodes are updated, the inactive subnode will be removed from the node, updated, rebooted if necessary, and then rejoined to the node. Then hosted servers will migrate to the now-updated subnode, and the process repeated for the other subnode. Anvil! nodes are updated sequentially, so the process can take some time to complete, but should not require a maintenance window.
.TP
The upgrade process will live-migrate all hosted servers! If any hosted server is either under heavy load, or the replication link (the BCN or MN) is relatively lower bandwidth, this could cause performance concerns. As such, it's ideal to run the upgrades at a time less sensitive to performance impacts.
.TP
.SH OPTIONS
.TP
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.SS "Commands:"
.TP
\fB\-\-clear\-cache\fR
.TP
This will force the dnf cache to be cleared before the OS update is started. This slows the update down a bit, but ensures the latest updates are installed.
.TP
\fB\-\-force\fR
.TP
If any Striker dashboards or DR hosts are unavailable, or if an entire node (paired subnodes) is offline, this switch will allow you to force the upgrade attempt.
.TP
\fB\-y\fR, \fB\-\-yes\fR
.TP
Automatically continue with the upgrade without prompting for confirmation.
.TP
\fB\-\-no\-reboot\fR
.TP
If the kernel is updated on a remote system, the system will normally be rebooted. This switch prevents the reboot from occuring.
.TP
\fB\-\-reboot\-self\fR
.TP
By default, if the local system needs to be updated, a message is printed but the local system is NOT rebooted. This switch will instead cause this host to reboot at the end of the cluster update.
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
