.\" Manpage for the Anvil! IA platform 
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH striker-file-manager "8" "August 15 2024" "Anvil! Intelligent Availability™ Platform"
.SH NAME
striker-file-manager \- This manages the files available for use by servers
.SH SYNOPSIS
.B striker-file-manager 
\fI\,<command>
.SH DESCRIPTION
This manages the files that are available to servers. These can be install ISO discs, driver discs, etc.
.IP
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log\-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.IP
.SH "Commands:"
This tool takes no other switches.
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
