.\" Manpage for the Anvil! IA platform 
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH striker-db-status "8" "July 23 2024" "Anvil! Intelligent Availability™ Platform"
.SH NAME
striker-db-status \- This shows the current status of striker dashboards
.SH SYNOPSIS
.B striker-db-status 
\fI\,<command>
.SH DESCRIPTION
This tool simply reports the current status of the striker dashboards and their databases. The output is meant to be machine parsable.
.IP
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log\-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.IP
.SH "Commands:"
This tool as no other switches.
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
