.\" Manpage for the Anvil! IA platform 
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH striker-manage-peers "8" "August 15 2024" "Anvil! Intelligent Availability™ Platform"
.SH NAME
striker-manage-peers \- This manages peering two Striker dashboards
.SH SYNOPSIS
.B striker-manage-peers 
\fI\,<command> \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
This handles peering Striker dashboards. Peered Strikers means that they act as replaceable alternative dashboards, should another fail.
.IP
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log\-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.IP
.SS "Commands:"
\fB\-\-check\fR
This reports 'status=[1,0]' to indicate if the install target feature is currently running or not. Specifically, it checks to see if the DHCP server is running or not.
.TP
\fB\-\-disable\fR
This disables the install target feature.
.TP
\fB\-\-enable\fR
This enables the install target feature.
.TP
\fB\-\-force\fR
This is the same as '--refresh', forcing the update of the RPM repo.
.TP
\fB\-\-job\-uuid\fR <uuid>
This is the job UUID used to run this job.
.TP
\fB\-\-no\-refresh\fR
If a refresh of the RPM repository would have been called, this switch will prevent it from happening.
.TP
\fB\-\-refresh\-file\fR
This tells this run to refresh the RPM repository, regardless of whether it would have run otherwise.
.TP
\fB\-\-status\fR
This checks to see if dhcpd is running or not, then exits (effectively checking if the install target feature is running).
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
