.\" Manpage for the Anvil! IA platform 
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH striker-get-peer-data "8" "July 23 2024" "Anvil! Intelligent Availability™ Platform"
.SH NAME
striker-get-peer-data \- This manages peering two Striker dashboards
.SH SYNOPSIS
.B striker-get-peer-data 
\fI\,<command> \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
This handles peering Striker dashboards. Peered Strikers means that they act as replaceable alternative dashboards, should another fail.
.TP
.B Note
The list that is downloaded is - https://standards-oui.ieee.org/oui/oui.txt 
.TP
The oui.txt file is cached locally once downloaded to minimizing loading the IEEE server. It will be redownloaded every few days.
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.SS "Commands:"
\fB\-\-target\fR

.TP
\fB\-\-state\-uuid\fR <uuid>

.TP
\fB\-\-password\fR "<password>"

.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
