.\" Manpage for the Anvil! Striker dashboard screenshot collection tool
.\" Contact mkelly@alteeve.com to report issues, concerns or suggestions.
.TH striker-get-screenshots "8" "September 12 2023" "Anvil! Intelligent Availability™ Platform"
.SH NAME
striker-get-screenshots \- Tool used to collect screenshots from Anvil! subnodes and DR hosts
.SH SYNOPSIS
.B striker-get-screenshots 
\fI\,<command> \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
striker-get-screenshots \- This uses the libvirtd API to collect screenshots from servers running on Anvil! subnodes and DR hosts. These are used to display periodic views into servers on the Striker dashboard.
.IP
.SH OPTIONS
\-?, \-h, \fB\-\-help\fR
Show this man page.
.TP
\fB\-\-log\-secure\fR
When logging, record sensitive data, like passwords.
.TP
\-v, \-vv, \-vvv
Set the log level to 1, 2 or 3 respectively. Be aware that level 3 generates a significant amount of log data.
.IP
.SS "Commands:"
\fB\-\-job\-uuid\fR
This is the jobs -> job_uuid to execute. Generally this is only used by other programs.
.IP
.SH AUTHOR
Written by Madison Kelly, Alteeve staff and the Anvil! project contributors.
.SH "REPORTING BUGS"
Report bugs to users@clusterlabs.org
